### ISSUE TITLE
Inference stage?

### ISSUE THREAD

**Issue by xthyax** [YanFangCS/CyCTR-Pytorch#5]
Hi, congrats on your great work, I seem a little late to the party. Still, after looking around, I can't figure out how to make an inference about an unlabeled image (an image that doesn't contain any prior information about the label).

My question is how can I run inference on unlabel images? Cause there will be no support images for the unlabeled image. And what is the practical way to work around this if not implemented yet?

**Comment by GengDavid** [comment]
Hi, thanks for your interest. If no support images are given, you may need a zero-shot model rather than a few-shot model.

**Comment by xthyax** [comment]
Hi, thanks for your kind reply. I'll look into that method.
